CREATE TABLE IF NOT EXISTS alpha_homora_pools_scrape (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp TIMESTAMP,
    chain text,
    strategy text,
    pool text,
    protocol text,
    leverage_min float NULL,
    leverage_max float NULL,
    leverage_highest_apr float NULL,
    apr_min float NULL,
    apr_max float NULL,
    apy_trading_fee float NULL,
    apr_farming float NULL,
    apr_reward float NULL,
    apy_borrow float NULL,
    trading_volume_24h float NULL,
    tvl_pool float NULL,
    tvl_homora float NULL,
    positions int NULL,
    INDEX idx_timestamp (timestamp),	
    INDEX idx_pool (pool),
    INDEX idx_chain (chain),
    INDEX idx_protocol (protocol),
    INDEX idx_name (pool)
)  ENGINE=INNODB;
